server {

    listen 80 default_server;

    # for api routes
    location ^~ /api {
        proxy_pass http://app:5000;
    }

    # for web routes
    location ^~ / {
        proxy_pass http://app:5000;
    }
}
